/*
 * trace/trace-hw_xbox_mcpx_apu_dsp.h shim for the pinned xemu DSP56300 sources
 * (A4b1 step 2).
 *
 * Upstream this file is generated by the QEMU tracetool from trace-events. Here
 * it is a shim, and it is a NO-OP: this toolkit has no trace backend, so every
 * event is compiled out.
 *
 * The four events the pinned code calls, and their call sites:
 *   trace_dsp_read_peripheral(addr, value)          dsp.c:71   (every peripheral read)
 *   trace_dsp_write_peripheral(addr, value)         dsp.c:103  (every peripheral write)
 *   trace_dsp56k_execute_instruction(is_gp, pc)     dsp_cpu.c:593 (every instruction)
 *   trace_dsp56k_execute_instruction_disasm(text)   dsp_cpu.c:612
 * plus trace_event_get_state() at dsp_cpu.c:605.
 *
 * trace_dsp56k_execute_instruction is on the interpreter's hot path, so a no-op
 * macro is not just honest here, it is required: a real function call per
 * retired instruction would change the port's cost by orders of magnitude.
 *
 * Device semantics 6's GP input accounting is NOT implemented here. It is
 * recorded at the pinned call sites themselves, in the ledger owned by
 * src/apu/apu_watch.c, so that AC-PORT step 4 can name the hook line for each
 * input kind and AC-FIX (viii) can exercise each one through the production
 * path. Putting the accounting behind a trace macro would make the ledger's
 * completeness depend on a header this file owns.
 */

#ifndef XBOXRECOMP_SHIM_TRACE_HW_XBOX_MCPX_APU_DSP_H
#define XBOXRECOMP_SHIM_TRACE_HW_XBOX_MCPX_APU_DSP_H

#include "qemu/osdep.h"

#define TRACE_DSP_READ_PERIPHERAL 0
#define TRACE_DSP_WRITE_PERIPHERAL 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM 0

#define trace_dsp_read_peripheral(addr, value)          ((void)0)
#define trace_dsp_write_peripheral(addr, value)         ((void)0)
#define trace_dsp56k_execute_instruction(is_gp, pc)     ((void)0)
#define trace_dsp56k_execute_instruction_disasm(text)   ((void)0)

/* Always false: there is no trace backend, so no event is ever enabled. */
#define trace_event_get_state(id) (0)

#endif /* XBOXRECOMP_SHIM_TRACE_HW_XBOX_MCPX_APU_DSP_H */
